let currentCard=0, quizIndex=0, quizScore=0;
document.addEventListener('DOMContentLoaded',()=>{const p=JK.requireAuth();if(!p)return;renderLetters();renderFlashcard();renderMatching();renderQuiz();});
function childOrWarn(){const c=JK.selectedChild();if(!c)JK.toast('Sila tambah profil anak dahulu.');return c}
function renderLetters(){const el=document.querySelector('#letterGrid');if(!el)return;el.innerHTML=JK.letters.map(([j,n])=>`<button class="letter" onclick="learnLetter('${j}','${n}')"><div>${j}</div><small>${n}</small></button>`).join('')}
function learnLetter(j,n){const c=childOrWarn();if(!c)return;JK.addXP(c.id,5,'Huruf Jawi');JK.toast(`${n} — +5 XP`)}
function renderFlashcard(){const el=document.querySelector('#flashcardBox');if(!el)return;const [j,n]=JK.letters[currentCard%JK.letters.length];el.innerHTML=`<div><div>${j}</div><p class="muted">Klik untuk lihat nama</p></div>`;el.onclick=()=>{el.innerHTML=`<div><div style="font-size:42px">${n}</div><p class="muted">${j}</p></div>`;const c=childOrWarn();if(c)JK.addXP(c.id,2,'Flash Card')};const next=document.querySelector('#nextCard');if(next)next.onclick=()=>{currentCard++;renderFlashcard()}}
function renderMatching(){const el=document.querySelector('#matchingBox');if(!el)return;const item=JK.letters[Math.floor(Math.random()*JK.letters.length)];const opts=[item[1],...JK.letters.filter(x=>x[1]!==item[1]).sort(()=>.5-Math.random()).slice(0,3).map(x=>x[1])].sort(()=>.5-Math.random());el.innerHTML=`<div class="card"><div class="jawi-big">${item[0]}</div><h3>Pilih sebutan yang betul</h3><div class="grid grid-2">${opts.map(o=>`<button class="option" onclick="answerMatch(this,'${o}','${item[1]}')">${o}</button>`).join('')}</div></div>`}
function answerMatch(btn,ans,correct){const c=childOrWarn();if(ans===correct){btn.classList.add('correct');if(c)JK.addXP(c.id,10,'Matching Game');JK.toast('Betul! +10 XP');setTimeout(renderMatching,800)}else{btn.classList.add('wrong');JK.toast('Cuba lagi.')}}
function renderQuiz(){const el=document.querySelector('#quizBox');if(!el)return;const q=JK.questions[quizIndex%JK.questions.length];el.innerHTML=`<div class="card"><p class="muted">Soalan ${quizIndex+1}/${JK.questions.length}</p><h2>${q.q}</h2><div class="grid grid-2">${q.o.map(o=>`<button class="option" onclick="answerQuiz(this,'${o.replace(/'/g,"\\'")}','${q.a.replace(/'/g,"\\'")}')">${o}</button>`).join('')}</div><p>Skor: <b>${quizScore}</b></p></div>`}
function answerQuiz(btn,ans,correct){const c=childOrWarn();if(ans===correct){quizScore++;btn.classList.add('correct');if(c)JK.addXP(c.id,20,'Quiz Jawi');}else btn.classList.add('wrong');setTimeout(()=>{quizIndex++;if(quizIndex>=JK.questions.length){const child=childOrWarn();const s=JK.load();if(child)s.quiz_results.push({id:JK.id('quiz'),child_id:child.id,quiz_type:'MVP',score:quizScore,correct:quizScore,wrong:JK.questions.length-quizScore,duration:0,created_at:new Date().toISOString()});JK.save(s);document.querySelector('#quizBox').innerHTML=`<div class="card"><h2>Keputusan Quiz</h2><p>Markah: <b>${quizScore}/${JK.questions.length}</b></p><button class="btn" onclick="location.reload()">Ulang Quiz</button></div>`;}else renderQuiz();},700)}
